### PR TITLE
Added support for Scientific Linux

### PR DESCRIPTION
**Pull request by apazga**
Just adding Scientific as "operatingsystem".

Thanks in advance.

### CODE REVIEW

**Comment by roman-mueller** [comment]
Hi,

would you mind adding it also to the supported OS list in [metadata.json](https://github.com/roman-mueller/rmueller-cron/blob/master/metadata.json)?
I think the identifier there is:
```
      "operatingsystem": "Scientific Linux",
```

**Comment by apazga** [comment]
Updated! (Just tested and operatingsystem fact shows "Scientific".)
Thanks!

**Comment by roman-mueller** [comment]
Thanks, you are right.
At first glance I don't think the failed tests are because of your commit.
I'll plan to look into this and get it merged/released on the weekend.

**Comment by apazga** [comment]
Thank you very much!

**Pull request merged**
